version: '3'

services:
  mysql:
    build: ./mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    # volumes:
    #   - ./mysql/data:/var/lib/mysql
    healthcheck:
      test: "exit 0"
  budgeteala:
    build: ./
    depends_on:
      - mysql
    environment:
      - NODE_ENV=production
      - BUDGETEALA_PORT=5000
      - BUDGETEALA_SECRET=budgeteala_secret
      - BUDGETEALA_VERSION=0.0.1
      - BUDGETEALA_AUTH_COOKIE=bauth
      - DB_USERNAME=budgeteala
      - DB_PASSWORD=budgeteala
      - DB_NAME=budgeteala
      - DB_HOST=mysql
      - DB_LOGGING=false
      - DB_DIALECT=mysql
    volumes:
      - ./app:/usr/src/app
    ports:
      -  5000:5000
      -  9229:9229